"""add teach_logs table

Revision ID: 16fe6f024228
Revises: 3145ef6babb7
Create Date: 2026-07-01 09:45:55.100854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16fe6f024228'
down_revision: Union[str, None] = '3145ef6babb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teach_logs',
    sa.Column('teach_log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('teach_log_id')
    )
    op.create_index('idx_teach_logs_grade', 'teach_logs', ['customer_id', 'grade_id', 'section'], unique=False)
    op.create_index('idx_teach_logs_topic', 'teach_logs', ['customer_id', 'subject_id', 'topic_id'], unique=False)
    op.create_index('idx_teach_logs_user', 'teach_logs', ['user_id'], unique=False)
    op.create_index('idx_teach_logs_user_date', 'teach_logs', ['user_id', 'date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teach_logs_user_date', table_name='teach_logs')
    op.drop_index('idx_teach_logs_user', table_name='teach_logs')
    op.drop_index('idx_teach_logs_topic', table_name='teach_logs')
    op.drop_index('idx_teach_logs_grade', table_name='teach_logs')
    op.drop_table('teach_logs')
    # ### end Alembic commands ###
