"""add subjects topics qa account_topics

Revision ID: 1c45e36b84dc
Revises: b9a89ad018cb
Create Date: 2026-06-15 11:26:17.485659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c45e36b84dc'
down_revision: Union[str, None] = 'b9a89ad018cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('subject_id', 'topic_name')
    )
    op.create_index('idx_topics_subject', 'topics', ['subject_id'], unique=False)
    op.create_table('qa',
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(question_type = 'mcq' AND options IS NOT NULL) OR (question_type != 'mcq' AND options IS NULL)", name='chk_options'),
    sa.CheckConstraint("question_type IN ('descriptive', 'mcq', 'true_false')", name='chk_question_type'),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='chk_difficulty'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('qa_id')
    )
    op.create_index('idx_qa_grade', 'qa', ['grade_id'], unique=False)
    op.create_index('idx_qa_subject_topic', 'qa', ['subject_id', 'topic_id'], unique=False)
    op.create_index('idx_qa_type', 'qa', ['question_type'], unique=False)
    op.create_index('idx_qa_verified', 'qa', ['is_verified'], unique=False)
    op.create_table('account_topics',
    sa.Column('account_topic_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('grade_relevant_to_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(customer_id IS NOT NULL AND user_id IS NULL) OR (user_id IS NOT NULL AND customer_id IS NULL)', name='chk_account'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['grade_relevant_to_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_topic_id')
    )
    op.create_index('idx_acct_topics_customer', 'account_topics', ['customer_id'], unique=False)
    op.create_index('idx_acct_topics_user', 'account_topics', ['user_id'], unique=False)
    op.create_index('uidx_acct_topics_customer', 'account_topics', ['customer_id', 'subject_id', 'topic_id', 'grade_id'], unique=True, postgresql_where=sa.text('customer_id IS NOT NULL'))
    op.create_index('uidx_acct_topics_user', 'account_topics', ['user_id', 'subject_id', 'topic_id', 'grade_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uidx_acct_topics_user', table_name='account_topics', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uidx_acct_topics_customer', table_name='account_topics', postgresql_where=sa.text('customer_id IS NOT NULL'))
    op.drop_index('idx_acct_topics_user', table_name='account_topics')
    op.drop_index('idx_acct_topics_customer', table_name='account_topics')
    op.drop_table('account_topics')
    op.drop_index('idx_qa_verified', table_name='qa')
    op.drop_index('idx_qa_type', table_name='qa')
    op.drop_index('idx_qa_subject_topic', table_name='qa')
    op.drop_index('idx_qa_grade', table_name='qa')
    op.drop_table('qa')
    op.drop_index('idx_topics_subject', table_name='topics')
    op.drop_table('topics')
    op.drop_table('subjects')
    # ### end Alembic commands ###
