"""add subject_areas, scope topics by area

Revision ID: 2b592e743e3a
Revises: 7c67fae49c22
Create Date: 2026-06-16 09:46:34.105574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b592e743e3a'
down_revision: Union[str, None] = '7c67fae49c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_areas',
    sa.Column('subject_area_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('subject_area_id'),
    sa.UniqueConstraint('subject_id', 'area_name')
    )
    op.create_index('idx_subject_areas_subject', 'subject_areas', ['subject_id'], unique=False)
    op.add_column('topics', sa.Column('subject_area_id', sa.Integer(), nullable=False))
    op.drop_index('uidx_topics_name_country', table_name='topics', postgresql_where='(country_id IS NOT NULL)')
    op.create_index('uidx_topics_name_country', 'topics', ['subject_area_id', 'topic_name', 'country_id'], unique=True, postgresql_where=sa.text('country_id IS NOT NULL'))
    op.drop_index('uidx_topics_name_universal', table_name='topics', postgresql_where='(country_id IS NULL)')
    op.create_index('uidx_topics_name_universal', 'topics', ['subject_area_id', 'topic_name'], unique=True, postgresql_where=sa.text('country_id IS NULL'))
    op.create_index('idx_topics_subject_area', 'topics', ['subject_area_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'subject_areas', ['subject_area_id'], ['subject_area_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index('idx_topics_subject_area', table_name='topics')
    op.drop_index('uidx_topics_name_universal', table_name='topics', postgresql_where=sa.text('country_id IS NULL'))
    op.create_index('uidx_topics_name_universal', 'topics', ['subject_id', 'topic_name'], unique=True, postgresql_where='(country_id IS NULL)')
    op.drop_index('uidx_topics_name_country', table_name='topics', postgresql_where=sa.text('country_id IS NOT NULL'))
    op.create_index('uidx_topics_name_country', 'topics', ['subject_id', 'topic_name', 'country_id'], unique=True, postgresql_where='(country_id IS NOT NULL)')
    op.drop_column('topics', 'subject_area_id')
    op.drop_index('idx_subject_areas_subject', table_name='subject_areas')
    op.drop_table('subject_areas')
    # ### end Alembic commands ###
