"""add quizzes quiz_scores quiz_challenges batch_jobs and qa.expected_time_seconds

Revision ID: 41960297c7a7
Revises: 2b592e743e3a
Create Date: 2026-06-16 11:13:58.002873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41960297c7a7'
down_revision: Union[str, None] = '2b592e743e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_scored', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index('idx_quizzes_student', 'quizzes', ['student_id'], unique=False)
    op.create_index('idx_quizzes_topic', 'quizzes', ['topic_id'], unique=False)
    op.create_table('quiz_challenges',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('challenge_reason', sa.Text(), nullable=False),
    sa.Column('challenge_response', sa.Text(), nullable=True),
    sa.Column('is_upheld', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['qa.qa_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    op.create_index('idx_quiz_challenges_qa', 'quiz_challenges', ['qa_id'], unique=False)
    op.create_index('idx_quiz_challenges_quiz', 'quiz_challenges', ['quiz_id'], unique=False)
    op.create_table('quiz_scores',
    sa.Column('quiz_score_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('qa_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('student_response', sa.Text(), nullable=True),
    sa.Column('marks', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('is_scored', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qa_id'], ['qa.qa_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.PrimaryKeyConstraint('quiz_score_id'),
    sa.UniqueConstraint('quiz_id', 'qa_id')
    )
    op.create_index('idx_quiz_scores_qa', 'quiz_scores', ['qa_id'], unique=False)
    op.create_index('idx_quiz_scores_quiz', 'quiz_scores', ['quiz_id'], unique=False)
    op.create_table('batch_jobs',
    sa.Column('batch_job_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('custom_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('qa_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['quiz_challenges.challenge_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['qa_id'], ['qa.qa_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('batch_job_id')
    )
    op.create_index('idx_batch_jobs_country', 'batch_jobs', ['country_id'], unique=False)
    op.create_index('idx_batch_jobs_lookup', 'batch_jobs', ['request_type', 'is_active', 'is_closed', 'date_created'], unique=False)
    op.create_index('idx_batch_jobs_subject', 'batch_jobs', ['subject_id'], unique=False)
    op.create_index('idx_batch_jobs_topic', 'batch_jobs', ['topic_id'], unique=False)
    op.add_column('qa', sa.Column('expected_time_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa', 'expected_time_seconds')
    op.drop_index('idx_batch_jobs_topic', table_name='batch_jobs')
    op.drop_index('idx_batch_jobs_subject', table_name='batch_jobs')
    op.drop_index('idx_batch_jobs_lookup', table_name='batch_jobs')
    op.drop_index('idx_batch_jobs_country', table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index('idx_quiz_scores_quiz', table_name='quiz_scores')
    op.drop_index('idx_quiz_scores_qa', table_name='quiz_scores')
    op.drop_table('quiz_scores')
    op.drop_index('idx_quiz_challenges_quiz', table_name='quiz_challenges')
    op.drop_index('idx_quiz_challenges_qa', table_name='quiz_challenges')
    op.drop_table('quiz_challenges')
    op.drop_index('idx_quizzes_topic', table_name='quizzes')
    op.drop_index('idx_quizzes_student', table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
