"""add app_settings table

Revision ID: 7c67fae49c22
Revises: 7e3e58090d75
Create Date: 2026-06-16 09:18:46.514897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c67fae49c22'
down_revision: Union[str, None] = '7e3e58090d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table('app_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO app_settings (setting_key, setting_value, description) VALUES
        ('match_auto_accept_threshold', '0.98', 'Trigram similarity score above which a subject/topic match is auto-accepted without an LLM check'),
        ('match_llm_verify_floor',      '0.90', 'Trigram similarity score above which an ambiguous match is sent to the LLM for same/different disambiguation'),
        ('qa_count',                    '30',   'Total QA items generated per subject+topic+grade'),
        ('descriptive_pct',             '0.20', 'Share of qa_count that should be descriptive questions'),
        ('mcq_pct',                     '0.60', 'Share of qa_count that should be MCQ questions'),
        ('difficulty_default',          '[0.20,0.20,0.20,0.20,0.20]', 'Difficulty level 1-5 distribution for grades below the skew threshold'),
        ('difficulty_skewed',           '[0.10,0.10,0.10,0.30,0.40]', 'Difficulty level 1-5 distribution for grades at/above the skew threshold'),
        ('difficulty_skew_grade_threshold', '9', 'Grade at which the skewed (harder) difficulty distribution kicks in'),
        ('grade_relevant_to_increment', '2',    'Default +N applied to grade to compute grade_relevant_to for grades below the override bands'),
        ('grade_relevant_to_override_grade_6', '10', 'grade_relevant_to value forced for grades 6-7'),
        ('grade_relevant_to_override_grade_8', '12', 'grade_relevant_to value forced for grades 8 and above'),
        ('title_case_stopwords',        '["a","an","the","of","in","on","and","or","for","to","with","at","by","is","are"]', 'Words kept lowercase in title-cased subject/topic names unless first or last word'),
        ('llm_provider_map',            '{"validate":"groq","generate":"openai"}', 'Which provider handles each LLM purpose'),
        ('llm_model_map',               '{"groq":"llama-3.3-70b-versatile","openai":"gpt-4o"}', 'Which model each provider uses')
        ON CONFLICT (setting_key) DO NOTHING
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
