"""add country_id to subjects and topics

Revision ID: 7e3e58090d75
Revises: ccfbb994937d
Create Date: 2026-06-16 09:12:50.943151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3e58090d75'
down_revision: Union[str, None] = 'ccfbb994937d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_subject_name_key', 'subjects', type_='unique')
    op.create_index('idx_subjects_country', 'subjects', ['country_id'], unique=False)
    op.create_index('uidx_subjects_name_country', 'subjects', ['subject_name', 'country_id'], unique=True, postgresql_where=sa.text('country_id IS NOT NULL'))
    op.create_index('uidx_subjects_name_universal', 'subjects', ['subject_name'], unique=True, postgresql_where=sa.text('country_id IS NULL'))
    op.create_foreign_key(None, 'subjects', 'countries', ['country_id'], ['country_id'])
    op.add_column('topics', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint('topics_subject_id_topic_name_key', 'topics', type_='unique')
    op.create_index('idx_topics_country', 'topics', ['country_id'], unique=False)
    op.create_index('uidx_topics_name_country', 'topics', ['subject_id', 'topic_name', 'country_id'], unique=True, postgresql_where=sa.text('country_id IS NOT NULL'))
    op.create_index('uidx_topics_name_universal', 'topics', ['subject_id', 'topic_name'], unique=True, postgresql_where=sa.text('country_id IS NULL'))
    op.create_foreign_key(None, 'topics', 'countries', ['country_id'], ['country_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index('uidx_topics_name_universal', table_name='topics', postgresql_where=sa.text('country_id IS NULL'))
    op.drop_index('uidx_topics_name_country', table_name='topics', postgresql_where=sa.text('country_id IS NOT NULL'))
    op.drop_index('idx_topics_country', table_name='topics')
    op.create_unique_constraint('topics_subject_id_topic_name_key', 'topics', ['subject_id', 'topic_name'])
    op.drop_column('topics', 'country_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index('uidx_subjects_name_universal', table_name='subjects', postgresql_where=sa.text('country_id IS NULL'))
    op.drop_index('uidx_subjects_name_country', table_name='subjects', postgresql_where=sa.text('country_id IS NOT NULL'))
    op.drop_index('idx_subjects_country', table_name='subjects')
    op.create_unique_constraint('subjects_subject_name_key', 'subjects', ['subject_name'])
    op.drop_column('subjects', 'country_id')
    # ### end Alembic commands ###
