"""add boards board_id on customers students fix account_topics

Revision ID: ccfbb994937d
Revises: 1c45e36b84dc
Create Date: 2026-06-15 11:58:11.522913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfbb994937d'
down_revision: Union[str, None] = '1c45e36b84dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('board_code', sa.String(length=20), nullable=False),
    sa.Column('board_name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('board_id'),
    sa.UniqueConstraint('board_code', 'country_id')
    )
    op.add_column('account_topics', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_index('idx_acct_topics_user', table_name='account_topics')
    op.drop_index('uidx_acct_topics_user', table_name='account_topics', postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_acct_topics_student', 'account_topics', ['student_id'], unique=False)
    op.create_index('uidx_acct_topics_student', 'account_topics', ['student_id', 'subject_id', 'topic_id', 'grade_id'], unique=True, postgresql_where=sa.text('student_id IS NOT NULL'))
    op.drop_constraint('account_topics_user_id_fkey', 'account_topics', type_='foreignkey')
    op.drop_constraint('chk_account', 'account_topics', type_='check')
    op.create_foreign_key(None, 'account_topics', 'students', ['student_id'], ['student_id'])
    op.drop_column('account_topics', 'user_id')
    op.create_check_constraint(
        'chk_account', 'account_topics',
        '(customer_id IS NOT NULL AND student_id IS NULL) OR '
        '(student_id IS NOT NULL AND customer_id IS NULL)'
    )
    op.add_column('customers', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'boards', ['board_id'], ['board_id'])
    op.add_column('students', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'boards', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'board_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'board_id')
    op.drop_constraint('chk_account', 'account_topics', type_='check')
    op.add_column('account_topics', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'account_topics', type_='foreignkey')
    op.create_foreign_key('account_topics_user_id_fkey', 'account_topics', 'users', ['user_id'], ['user_id'])
    op.create_check_constraint(
        'chk_account', 'account_topics',
        '(customer_id IS NOT NULL AND user_id IS NULL) OR '
        '(user_id IS NOT NULL AND customer_id IS NULL)'
    )
    op.drop_index('uidx_acct_topics_student', table_name='account_topics', postgresql_where=sa.text('student_id IS NOT NULL'))
    op.drop_index('idx_acct_topics_student', table_name='account_topics')
    op.create_index('uidx_acct_topics_user', 'account_topics', ['user_id', 'subject_id', 'topic_id', 'grade_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index('idx_acct_topics_user', 'account_topics', ['user_id'], unique=False)
    op.drop_column('account_topics', 'student_id')
    op.drop_table('boards')
    # ### end Alembic commands ###
