// AUTO-GENERATED from error_codes.json by scripts/generate_error_codes.py — do not edit directly.

export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SUBJECT_TOPIC_INVALID: "SUBJECT_TOPIC_INVALID",
  GRADE_INVALID: "GRADE_INVALID",
  GRADE_NOT_OFFERED: "GRADE_NOT_OFFERED",
  LLM_TIMEOUT: "LLM_TIMEOUT",
  LLM_GENERATION_FAILED: "LLM_GENERATION_FAILED",
  LLM_INVALID_RESPONSE: "LLM_INVALID_RESPONSE",
  DB_CONNECTION_FAILED: "DB_CONNECTION_FAILED",
  DB_CONSTRAINT_VIOLATION: "DB_CONSTRAINT_VIOLATION",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  SCHOOL_NOT_ASSOCIATED: "SCHOOL_NOT_ASSOCIATED",
  LAST_SUPER_ADMIN: "LAST_SUPER_ADMIN",
  TEACHER_NOT_FOUND: "TEACHER_NOT_FOUND",
  NO_PENDING_VERIFICATION: "NO_PENDING_VERIFICATION",
  VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  INCORRECT_CODE: "INCORRECT_CODE",
  UNKNOWN_COUNTRY_CODE: "UNKNOWN_COUNTRY_CODE",
  QUIZ_NOT_FOUND: "QUIZ_NOT_FOUND",
  QA_NOT_FOUND: "QA_NOT_FOUND",
  DUPLICATE_ID: "DUPLICATE_ID",
  XLSX_FORMAT_INVALID: "XLSX_FORMAT_INVALID",
  XLSX_VALUE_MISSING: "XLSX_VALUE_MISSING",
  XLSX_FILE_TYPE_INVALID: "XLSX_FILE_TYPE_INVALID",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",
  EXTERNAL_SERVICE_FAILED: "EXTERNAL_SERVICE_FAILED",
  BATCH_JOB_FAILED: "BATCH_JOB_FAILED",
  FRONTEND_RUNTIME_ERROR: "FRONTEND_RUNTIME_ERROR",
  FRONTEND_NETWORK_ERROR: "FRONTEND_NETWORK_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorDefault {
  message: string;
  httpStatus: number;
}

export const ERROR_DEFAULTS: Record<ErrorCodeValue, ErrorDefault> = {
  VALIDATION_ERROR: { message: "The submitted data failed validation.", httpStatus: 400 },
  SUBJECT_TOPIC_INVALID: { message: "{reason}", httpStatus: 422 },
  GRADE_INVALID: { message: "The grade provided is not valid.", httpStatus: 400 },
  GRADE_NOT_OFFERED: { message: "No students are enrolled in Grade {grade} at your school.", httpStatus: 400 },
  LLM_TIMEOUT: { message: "The AI service did not respond in time. Please try again.", httpStatus: 504 },
  LLM_GENERATION_FAILED: { message: "Question generation failed. Please try again.", httpStatus: 502 },
  LLM_INVALID_RESPONSE: { message: "The AI service returned an unexpected response.", httpStatus: 502 },
  DB_CONNECTION_FAILED: { message: "A database connection error occurred.", httpStatus: 500 },
  DB_CONSTRAINT_VIOLATION: { message: "The requested change conflicts with existing data.", httpStatus: 409 },
  AUTH_REQUIRED: { message: "You must be signed in to do this.", httpStatus: 401 },
  AUTH_FORBIDDEN: { message: "You do not have permission to do this.", httpStatus: 403 },
  INVALID_CREDENTIALS: { message: "Incorrect login ID or password.", httpStatus: 401 },
  ACCOUNT_INACTIVE: { message: "This account is no longer active.", httpStatus: 401 },
  SCHOOL_NOT_ASSOCIATED: { message: "No school is associated with this account.", httpStatus: 400 },
  LAST_SUPER_ADMIN: { message: "At least one super admin must remain for this school.", httpStatus: 400 },
  TEACHER_NOT_FOUND: { message: "This teacher could not be found.", httpStatus: 404 },
  NO_PENDING_VERIFICATION: { message: "No pending verification found for this email.", httpStatus: 400 },
  VERIFICATION_CODE_EXPIRED: { message: "Your code has expired. Request a new one.", httpStatus: 410 },
  TOO_MANY_ATTEMPTS: { message: "Too many incorrect attempts. Please request a new code.", httpStatus: 400 },
  INCORRECT_CODE: { message: "Incorrect code. {remaining} attempt(s) remaining.", httpStatus: 400 },
  UNKNOWN_COUNTRY_CODE: { message: "Unknown country code: {code}", httpStatus: 400 },
  QUIZ_NOT_FOUND: { message: "This quiz could not be found.", httpStatus: 404 },
  QA_NOT_FOUND: { message: "This question could not be found.", httpStatus: 404 },
  DUPLICATE_ID: { message: "{id} already in use. Check all ids.", httpStatus: 400 },
  XLSX_FORMAT_INVALID: { message: "Incorrect xlsx format. Check column headings and values.", httpStatus: 400 },
  XLSX_VALUE_MISSING: { message: "Id, name and {field} must be entered.", httpStatus: 400 },
  XLSX_FILE_TYPE_INVALID: { message: "Please upload an .xlsx file.", httpStatus: 400 },
  EMAIL_ALREADY_USED: { message: "{email} is already used by another teacher.", httpStatus: 400 },
  EXTERNAL_SERVICE_FAILED: { message: "An external service failed to respond correctly.", httpStatus: 502 },
  BATCH_JOB_FAILED: { message: "A background job failed to complete.", httpStatus: 500 },
  FRONTEND_RUNTIME_ERROR: { message: "Something went wrong on the page. Please refresh and try again.", httpStatus: 500 },
  FRONTEND_NETWORK_ERROR: { message: "Could not reach the server. Please check your connection.", httpStatus: 503 },
  UNKNOWN_ERROR: { message: "An unexpected error occurred.", httpStatus: 500 },
};
